# azure-pipelines.yml
trigger:
  - main

pr:
  - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - checkout: self

          - script: echo "Azure Pipelines Execution - Build and Test the repo"
            displayName: 'Run a one-line script'

          - task: NodeTool@0
            displayName: 'Use Node.js 24'
            inputs:
              versionSpec: '24.x'

          - task: Cache@2
            displayName: 'Cache node_modules'
            inputs:
              key: 'node_modules | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                node_modules | "$(Agent.OS)"
              path: '$(Build.SourcesDirectory)/node_modules'

          - script: |
              npm install -g @usebruno/cli
            displayName: 'Install Bruno CLI'
